### ISSUE TITLE
Video full screen in Firefox

### ISSUE THREAD

**Issue by miranca** [yairEO/photobox#100]
Hi guys, it seems that video playback on full screen in Firefox is not working fine, the width of the video does not expand (I'm using v. 38.0.5)

**Comment by yairEO** [comment]
there is no "guys" it's just me.. also, when saying "videos", which companies do you mean exactly? I am guessing it's Vimeo.

**Comment by miranca** [comment]
Oh, sorry.. I was using YouTube, but Vimeo looks the same on the demo page

**Comment by yairEO** [comment]
I don't see any solution to this issue. it's not about photobox at all, but an unfortunate mix of things. the video is most likely an iframe, sitting inside some container which happens to have some set of CSS rules. I cannot know when a video goes fullscreen, therefor I cannot fix this issue when fullscreen is triggered..unfortunately. 

BUT I designed photobox so photos and videos could be "zoomed", so just use your mousewheel (preferably outside of the video area, since it captures the mouse wheel event from inside, and not allowing my code to do it's job). This will enlarge the video for you. it's not so intuitive but I don't know what else to do.

**Comment by miranca** [comment]
Yes, I saw that Chrome adds its native user agent full-screen  styles for the iframe and its parent container and forces them to get 100%, and Firefox does not do that by default.. I was hoping there was a quick fix for FF as well. Anyway, thanks for your time, and the plugin!
