### ISSUE TITLE
Add icons to share on social networks

### ISSUE THREAD

**Issue by pedro1958** [yairEO/photobox#117]
I'm using a Wordpress plugin that uses photobox v1.9.12, pictures and videos shown, I need share on social networks.
How do I add icons?
Thanks, greetings from Chile.

**Comment by yairEO** [comment]
what wordpress plugin???

**Comment by pedro1958** [comment]
It's Smart Grid Responsive Gallery plugin topdevs.net bought http://codecanyon.net/, reviewing and photobox.css jquery.photobox.js are the same codes of this repository.
Thank you.

**Comment by yairEO** [comment]
Thanks. I've taken it down from codecanyon since this person stole my code and sold it as his.

**Comment by topdevs** [comment]
We did not sell Photobox as our code, we were selling it as part of more complex product. We added links to this project in the plugin docs, kept the attribution in the script files and added credits with a link on the item page. We never said that we code Photobox.

If you don't want other developers to use your script in commercial purposes, remove the MIT license reference from all the script files, like this:

**jquery.photobox.js**

```
/*!
    photobox v1.9.12
    (c) 2013 Yair Even Or <http://dropthebit.com>

    MIT-style license.
*/
```

or **index.html**

```
/*
 * Photobox
 *
 * Copyright 2012, Yair Even Or
 * https://dropthebit.com
 *
 * Licensed under the MIT license:
 * http://www.opensource.org/licenses/MIT
 */
```

Because MIT license give others: **rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software**. See http://www.opensource.org/licenses/MIT for the full text.

There are more plugins with Photobox included selling over the Internet. Maybe this wouldn't happen if you set a proper license.

**Comment by yairEO** [comment]
These licenses are for the DEMO page, not the javascript code, which is in Github, and goes by the github license. the `jquery.photobox.js` file is irrelevant and is to be ignored.  (i have removed the license). I have contacted other developers you have stolen from and they are all furious and are in the process of going to war with you.
