### ISSUE TITLE
Issue with reactjs ?

### ISSUE THREAD

**Issue by juanonsoftware** [yairEO/photobox#144]
Hi,
Thanks for the great library !
I want to use this with reactjs but having an issue: the thumbs at bottom is not visible, and in chrome console having an uncaught error: this.imageLinks.size is not a function at C.generate (jquery.photobox.js:452)
Any help would be highly appreciated. Thanks.

**Comment by juanonsoftware** [comment]
It looks like that v1.9.2 works. Not sure if that's a bug on newer releases. Thanks.

**Comment by yairEO** [comment]
Yes i think I know why, years ago I used the `size` method but it appears to have been deprecated since. I'll change it to `length`. I wrote this script back in 2012 and it's not so great today

**Comment by yairEO** [comment]
I don't see anywhere `this.imageLinks.size` in the source code of _photobox_

**Comment by digggggggggg** [comment]
I've had the same problem and this.imageLinks.size(); appears in the CDNJS hosted version of the plugin: https://cdnjs.cloudflare.com/ajax/libs/photobox/1.9.9/photobox/jquery.photobox.min.js

I believe it's from version 1.9.2.

Version 1.9.9 doesn't have this issue,
https://github.com/yairEO/photobox/blob/d60b862eb03d6ff1014949a443652ca79597ab51/photobox/jquery.photobox.js#L584

And the mix-up might have occurred because in your releases 1.9.2 appears later than 1.9.9
https://github.com/yairEO/photobox/releases


Would it be possible to address this?
