### ISSUE TITLE
Use repainting insteadOf waiting

### ISSUE THREAD

**Issue by TrySound** [yairEO/photobox#98]
https://github.com/yairEO/photobox/blob/master/photobox/jquery.photobox.js#L835
```js
elementOnThePage.offsetHeight;
```
This is the most popular trick to trigger repainting.

**Comment by yairEO** [comment]
yes I know this technique, but I intentionally don't use it because it does a `repaint` job, which I don't want to happen...I prefect a silent timeout which requires the least processing from the CPU for things which might happen frequently, like changing the current item (image or video). I do use this when it's something that is needed less frequently though
